# Homepage settings configuration
title: Home Server Dashboard
theme: dark
language: en
background: /img/backgrounds/default.jpg
logo: /img/logo.png
favicon: /img/favicon.png
headerStyle: center
layout: auto
disableAutofocus: false
disableCollapse: false
disableDrag: false
disableEdit: false
disableGrouping: false
disableSort: false
hideVersion: false
hideSearch: false
hideSettings: false
hideHelp: false
hideAll: false
hideAllServices: false
hideAllWidgets: false
hideAllBookmarks: false
hideAllIframes: false
hideAllApps: false
hideAllTools: false
hideAllGames: false
hideAllOther: false
hideAllCustom: false
hideAllCustom1: false
hideAllCustom2: false
hideAllCustom3: false
hideAllCustom4: false
hideAllCustom5: false
hideAllCustom6: false
hideAllCustom7: false
hideAllCustom8: false
hideAllCustom9: false
hideAllCustom10: false
hideAllCustom11: false
hideAllCustom12: false
hideAllCustom13: false
hideAllCustom14: false
hideAllCustom15: false
hideAllCustom16: false
hideAllCustom17: false
hideAllCustom18: false
hideAllCustom19: false
hideAllCustom20: false
hideAllCustom21: false
hideAllCustom22: false
hideAllCustom23: false
hideAllCustom24: false
hideAllCustom25: false
hideAllCustom26: false
hideAllCustom27: false
hideAllCustom28: false
hideAllCustom29: false
hideAllCustom30: false
hideAllCustom31: false
hideAllCustom32: false
hideAllCustom33: false
hideAllCustom34: false
hideAllCustom35: false
hideAllCustom36: false
hideAllCustom37: false
hideAllCustom38: false
hideAllCustom39: false
hideAllCustom40: false
hideAllCustom41: false
hideAllCustom42: false
hideAllCustom43: false
hideAllCustom44: false
hideAllCustom45: false
hideAllCustom46: false
hideAllCustom47: false
hideAllCustom48: false
hideAllCustom49: false
hideAllCustom50: false 